name: create build and deployment data

on:
  push:
    tags:
      - 'r/*'
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: echo Creating build and deployment data
